
package servicemgr;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceImplementation", targetNamespace = "http://ServiceMgr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceImplementation {


    Object delete = null;

	/**
     * 
     * @param arg3
     * @param i
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<servicemgr.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://ServiceMgr/", className = "servicemgr.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://ServiceMgr/", className = "servicemgr.UpdateResponse")
    @Action(input = "http://ServiceMgr/ServiceImplementation/updateRequest", output = "http://ServiceMgr/ServiceImplementation/updateResponse")
    public List<Student> update(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String i,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<servicemgr.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://ServiceMgr/", className = "servicemgr.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://ServiceMgr/", className = "servicemgr.DeleteResponse")
    @Action(input = "http://ServiceMgr/ServiceImplementation/deleteRequest", output = "http://ServiceMgr/ServiceImplementation/deleteResponse")
    public List<Student> delete(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param string
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<servicemgr.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://ServiceMgr/", className = "servicemgr.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://ServiceMgr/", className = "servicemgr.AddStudentResponse")
    @Action(input = "http://ServiceMgr/ServiceImplementation/addStudentRequest", output = "http://ServiceMgr/ServiceImplementation/addStudentResponse")
    public List<Student> addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String string,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @return
     *     returns java.util.List<servicemgr.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "show", targetNamespace = "http://ServiceMgr/", className = "servicemgr.Show")
    @ResponseWrapper(localName = "showResponse", targetNamespace = "http://ServiceMgr/", className = "servicemgr.ShowResponse")
    @Action(input = "http://ServiceMgr/ServiceImplementation/showRequest", output = "http://ServiceMgr/ServiceImplementation/showResponse")
    public List<Student> show();

	//public List<Student> addStudent(String arg0, String arg1, String string, String arg3);

}
